services:
  frontend:
    depends_on:
      - backend
    restart: always
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
      target: dev
    networks:
      - net
    ports:
      - "5173:5173"
    volumes:
      - FE_app:/app
      - /app/node_modules

  backend:
    restart: always
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
      target: dev
    networks:
      - net
    expose:
      - "3000"
    #ports:
    # - "3000:3000"
    volumes:
      - BE_app:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: always
    networks:
      - net
    expose:
    - "5432"
    # ports:
    #  - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - DB_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:  # optionnal but useful to debug
    image: dpage/pgadmin4
    restart: always
    networks:
      - net
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@transcendence.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  FE_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/frontend
  BE_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/backend
  DB_data:  # volume persistant pour les données
    driver: local

networks:
  net:
    driver: bridge