services:
  frontend:
    restart: always
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
      # dev requires 5173:5173 / prod requires 80:80
      target: dev
    networks:
      - net
    ports:
      - "5173:5173"
    volumes:
      - FE_app:/app
      - /app/node_modules

volumes:
  FE_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/frontend

networks:
  net:
    driver: bridge