export const PADDLE_SPEED = 480;      // 4 * 60
export const PADDLE_HEIGHT = 100;
export const PADDLE_WIDTH = 15;
export const PADDLE_SPACING = 20;
export const CANVAS_HEIGHT = 600;
export const CANVAS_WIDTH = 800;
export const BALL_SPEED = 120;         // 1 * 60
export const MAX_BALL_SPEED = 240;    // 2 * 60
export const BALL_ACCELERATION = 6;   // 0.05 * 60
export const BALL_SHIFTING = 60;      // 0.5 * 60
export const BALL_SIZE = 10;
export const BALL_IDK = 0;
export const SCORE_TO_WIN = 10;
export const SCORE_HEIGHT = 50;
export const FRAMERATE = 60;